/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/robotNaranja/cute_robot.glb -r -t public
Author: Studio Sazor (https://sketchfab.com/studiosazor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-robot-72357362eace4609bbc23d75f6603cab
Title: Cute robot
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_22: THREE.Mesh;
  };
  materials: {
    metal_blanco: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    pantalla: THREE.MeshPhysicalMaterial;
    fondo_ojos: THREE.MeshStandardMaterial;
    borde_ojos: THREE.MeshStandardMaterial;
    borde_cabeza_2: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    motores: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    pantalla_trasera: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    cubo_externp: THREE.MeshStandardMaterial;
  };
};

export function SceneRobotPC(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/robotNaranja/cute_robot.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.096}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.001, 1.31, 0.038]} scale={0.61}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.metal_blanco}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.pantalla}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials.fondo_ojos}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.borde_ojos}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials.borde_cabeza_2}
            />
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.motores}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials.pantalla_trasera}
            />
          </group>
          <group position={[0, -0.536, 5.688]} scale={[1.961, 1, 0.347]}>
            <mesh
              geometry={nodes.Object_19.geometry}
              material={materials.metal_blanco}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.material_0}
            position={[0, 4.135, 5.685]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={9.437}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials.cubo_externp}
            position={[-0.337, 2.965, -1.557]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.435, 0.435, 0.712]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/robotNaranja/cute_robot.glb");
